services:
  - type: web
    name: lienmart-chatbox
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        value: your_real_openai_api_key_here  # Thay bằng KEY thật trong Render Dashboard
    plan: free
